### ISSUE TITLE
Add Jaccard Similarity

### ISSUE THREAD

**Issue by toto6599** [18-1-SKKU-OSS/2018-1-OSS-E8#8]
There is no jaccard similarity function in 'similarity' module.
We should add this function;

**Comment by LeeWooJung** [comment]
from math import*
 
def jaccard_similarity(x,y):
 
    intersection_cardinality = len(set.intersection(*[set(x), set(y)]))
    union_cardinality = len(set.union(*[set(x), set(y)]))
    return intersection_cardinality/float(union_cardinality)

this can be a good metrics for calcualting jaccard similarity

**Comment by toto6599** [comment]
good jjoong haha
